spring:
  security:
    user:
      name: myuser
      password: mypassword

  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true  # Enables the H2 console
      path: /h2-console  # URL path to access the console
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    show-sql: true  # Show SQL queries in the console
